version: '3'
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: jeong1998#
      MYSQL_DATABASE: badgeroad
      MYSQL_USER: user
      MYSQL_PASSWORD: password